sudo: required
language: rust

cache: cargo

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

rust:
  - stable
  - nightly
  - beta

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo install cargo-update
  - cargo install cargo-travis
  - cargo install-update -a

script:
  - cargo build
  - cargo test
  - cargo bench

after_success:
  - cargo coveralls
  - cargo doc-upload
