sudo: required
language: rust
rust:
 - stable
 - nightly
cache: cargo
env:
  global:
   - secure: qikNsOJWrTN3/gopYiSXmA3ytTsQc48qbxs5ILWmQGF+SvfH0bFIvoR3HMTw2pMcRDrtBrur0BzX4LE92fYL4HU1KkNJ0ywA70SLOJlhetxTaahKwRpaQDP9wtdCcogyFa+TuqKtIXHSTGYgJwc5nJMxec9g7IK06g+9slfHnO67Fk7LzPs86ffZuGYV8S1cSYGslmpkb49UkyyrVxjKn379k1YcGH/wb/vqzi3XLgnpBUONfKUceKSlb7nPiAAqyzpbe+a9gJ9JfZPl9R/W1OhL9Q1RwDSDy5v6iqmO1E/O53Wj5P/PBTvIyWefKDaZS84Ue+N1CTarOnR+zvBWIt9NtE8FsuU2Ve7zzrD534MvuABOezLGX5dU9VFjo37SX6Jk9gyi1P87UJfkv1RCTrLp6w+3v42AH1T4XAEzeVxJDx0NM1XlsJaq4xo+Kiie9l+zizZGsBBWP87XC8+1hcz+2iZa0SzhUWK6kfUQh82pCdntvJaKbRyrHHDijbxtFDwsUnLEBUuxwg5pffYoYrnqzOTjAZEoCg6qPkmKvsiSe51Q/pxtGW5VFJ8awzdQNr+LZuOvWv1O6Hvs5ODIBQuifg2xS1DjfE+WKrmwqkoXacJtq7OZlQXE4r9r2TPLw7Q7JVHYqqaytxHQAZWGMG40cOkUIHVW7bZBIOK2vc8=
matrix:
  include:
   - rust: nightly
addons:
  apt:
    packages:
     - libcurl4-openssl-dev
     - libelf-dev
     - libdw-dev
     - binutils-dev
     - cmake
    sources:
     - kalakris-cmake
before_script:
 - export PATH=$HOME/.cargo/bin:$PATH
 - cargo install cargo-update || echo "cargo-update is already installed."
 - cargo install cargo-travis || echo "cargo-travis is already installed."
 - cargo install-update -a
script:
 - cargo build
 - cargo doc
 - cargo test
 - cargo bench
after_success:
 - cargo coveralls
 - cargo doc-upload
