[package]
name = "heliometer"
version = "0.2.1"
authors = [ "LEARAX57H <willculhane3@gmail.com>",
            "vpzomtrrfrt <eric@gloriouswill.com>" ]

[lib]
name = "heliometer"
path = "src/lib.rs"

[[bin]]
name = "helio"
path = "src/main.rs"

[dependencies]
