[package]
name = "heliometer"
version = "0.3.7"
description = "A basic brainfuck interpreter"
authors = [ "LEARAX57H <willculhane3@gmail.com>",
            "vpzomtrrfrt <eric@gloriouswill.com>" ]

keywords = ["bf", "brainfuck"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/PishLSDYUE/heliometer"

[lib]
name = "heliometer"
path = "src/lib.rs"

[[bin]]
name = "helio"
path = "src/main.rs"

[dependencies]
